todo named pipes; blocking and <(command) is file not fd

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
+export rcfile='gibberish.rc'
+
 command -v git &>/dev/null || (echo 'Install git' ; exit 1)
 command -v flock &>/dev/null || (echo 'Install flock' ; exit 1)
 command -v gpg &>/dev/null || (echo 'Install gpg' ; exit 1)
 
 code_dir="${BASH_SOURCE%/*}"
-. "${code_dir}/source_me.bash" || (echo 'Missing source_me.bash' ; exit 1)
+. "${code_dir}/${rcfile}" || (echo "Missing ${rcfile}" ; exit 1)
 rm -rf "${GIBBERISH_DIR}"
 
 echo 'You already have a repository in cloud, right?
@@ -69,9 +71,13 @@ git switch --quiet "${config}" &>/dev/null || \
 (git checkout --quiet -b "${config}"
 git commit --allow-empty -m 'Root commit'; git push --quiet origin "${config}")
 
-until git tag last_read &>/dev/null; do git tag -d last_read; done
+until git tag last_read &>/dev/null; do git tag -d last_read &>/dev/null; done
 
 # Create outgoing directory; checked out with appropriate branch
 git worktree add "${outgoing_dir}" "${talkto}" &>/dev/null || \
 (git worktree add --quiet -b "${talkto}" "${outgoing_dir}"
 git push --quiet origin "${talkto}")
+
+cp "${code_dir}/${rcfile}" "${HOME}/.${rcfile}"
+run_command=". ${HOME}/.${rcfile}"
+grep -x "${run_command}" "${HOME}/.bashrc" || echo "${run_command}" >> "${HOME}/.bashrc"
